Repository ArpadVS/KTS-NVT_tim9_2019, pull requests merged in 2019-11, with the labels that each got.

#6 file upload cloudinary api
  backend/backend/pom.xml
  backend/backend/src/main/java/backend/config/CloudinaryConfig.java
  backend/backend/src/main/java/backend/config/WebSecurityConfig.java
  backend/backend/src/main/java/backend/controller/AuthenticationController.java
  backend/backend/src/main/java/backend/controller/DogController.java
  backend/backend/src/main/java/backend/converters/RegistrationConverter.java
  backend/backend/src/main/java/backend/dto/DogDTO.java
  backend/backend/src/main/java/backend/dto/UserDTO.java
  backend/backend/src/main/java/backend/model/Dog.java
  backend/backend/src/main/java/backend/model/User.java
  backend/backend/src/main/java/backend/repository/DogRepository.java
  backend/backend/src/main/java/backend/service/AddressService.java
  backend/backend/src/main/java/backend/service/CustomUserDetailsService.java
  backend/backend/src/main/java/backend/service/DogService.java
  backend/backend/src/main/java/backend/service/EmailService.java
  backend/backend/src/main/java/backend/service/FileUploadService.java
  backend/backend/src/main/java/backend/service/UserService.java
  backend/backend/src/main/java/backend/service/impl/UserServiceImpl.java
  backend/backend/src/main/resources/application.properties
Labels: enhancement

#7 razbijanje zahteva na multipart i json deo
  backend/backend/src/main/java/backend/controller/DogController.java
  backend/backend/src/main/java/backend/controller/UserController.java
  backend/backend/src/main/java/backend/dto/DogDTO.java
  backend/backend/src/main/java/backend/model/Dog.java
  backend/backend/src/main/java/backend/repository/DogRepository.java
  backend/backend/src/main/java/backend/service/DogService.java
Labels: enhancement

#11 Event media
  backend/backend/src/main/java/backend/controller/EventController.java
  backend/backend/src/main/java/backend/converters/EventConverter.java
  backend/backend/src/main/java/backend/dto/EventDTO.java
  backend/backend/src/main/java/backend/model/Event.java
  backend/backend/src/main/resources/data.sql
Labels: enhancement

#12 upload velikih fajlova
  backend/backend/src/main/java/backend/config/CloudinaryConfig.java
  backend/backend/src/main/java/backend/service/FileUploadService.java
  backend/backend/src/main/resources/application.properties
Labels: improvement

#14 Generic exception handling
  backend/backend/src/main/java/backend/controller/AuthenticationController.java
  backend/backend/src/main/java/backend/controller/UserController.java
  backend/backend/src/main/java/backend/exceptions/BadRequestException.java
  backend/backend/src/main/java/backend/exceptions/ResourceNotFoundException.java
  backend/backend/src/main/java/backend/exceptions/UserAlreadyExistsException.java
  backend/backend/src/main/java/backend/exceptions/UserNotFoundException.java
  backend/backend/src/main/java/backend/exceptions/handler/CustomErrorResponse.java
  backend/backend/src/main/java/backend/exceptions/handler/GlobalExceptionHandler.java
  backend/backend/src/main/java/backend/service/UserService.java
Labels: refactoring

#15 simultani upload json + multipart-data
  backend/backend/src/main/java/backend/controller/AuthenticationController.java
  backend/backend/src/main/java/backend/converters/RegistrationConverter.java
  backend/backend/src/main/java/backend/service/UserService.java
Labels: improvement

#16 brisanje slika iz baze i sa clouda
  backend/backend/src/main/java/backend/config/CloudinaryConfig.java
  backend/backend/src/main/java/backend/controller/EventController.java
  backend/backend/src/main/java/backend/dto/UrlDTO.java
  backend/backend/src/main/java/backend/service/FileUploadService.java
Labels: enhancement

#17 brisanje upload-ovanih slika i videa iz baze i sa cloud-a
  backend/backend/src/main/java/backend/config/CloudinaryConfig.java
  backend/backend/src/main/java/backend/controller/EventController.java
  backend/backend/src/main/java/backend/service/FileUploadService.java
Labels: enhancement

#18 Scheduler feature
  backend/backend/src/main/java/backend/BackendApplication.java
  backend/backend/src/main/java/backend/config/CloudinaryConfig.java
  backend/backend/src/main/java/backend/controller/AddressController.java
  backend/backend/src/main/java/backend/controller/EventController.java
  backend/backend/src/main/java/backend/controller/EventDayController.java
  backend/backend/src/main/java/backend/controller/ReservationController.java
  backend/backend/src/main/java/backend/controller/SchedulerController.java
  backend/backend/src/main/java/backend/converters/EventConverter.java
  backend/backend/src/main/java/backend/converters/HallConverter.java
  backend/backend/src/main/java/backend/converters/SectorConverter.java
  backend/backend/src/main/java/backend/dto/EventDTO.java
  backend/backend/src/main/java/backend/model/Administrator.java
  backend/backend/src/main/java/backend/model/RegisteredUser.java
  backend/backend/src/main/java/backend/model/Reservation.java
  backend/backend/src/main/java/backend/repository/EventRepository.java
  backend/backend/src/main/java/backend/repository/ReservationRepository.java
  backend/backend/src/main/java/backend/repository/TicketRepository.java
  backend/backend/src/main/java/backend/service/ChartService.java
  backend/backend/src/main/java/backend/service/EmailService.java
  backend/backend/src/main/java/backend/service/EventService.java
  backend/backend/src/main/java/backend/service/FileUploadService.java
  backend/backend/src/main/java/backend/service/ReservationService.java
  backend/backend/src/main/java/backend/service/SchedulerService.java
  backend/backend/src/main/resources/application.properties
  backend/backend/src/main/resources/data.sql
Labels: enhancement
